name: Tests
on: [ push ]
jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        operating-system: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ds,mbstring
          ini-values: memory_limit=1G

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Run tests"
        run: "./vendor/bin/phpunit tests"

      - name: "Run phpstan"
        run: "./vendor/bin/phpstan analyse src --level 9"